config:
  name: qwen2.5-vl-3B-nuplan-grpo
  description: DriveVLA based on Qwen 2.5 VL 3B model GRPO fine-tuning on NuPlan dataset
  model:
    use_cot: true
    pretrained_model_path: /data/tianhui/Qwen/Qwen2.5-VL-3B-Instruct
    sft_model_path: /data/zewei/DriveVLA_RLFT/sft_checkpoints/cot0/epoch3-loss0.5807.ckpt
    codebook_cache_path: codebook_cache/agent_vocab.pkl
    train_vision_backbone: false
    train_lm_backbone: true
    lora:
      use: true
      task_type: CAUSAL_LM
      target_modules:
      - q_proj
      - v_proj
      - k_proj
      - o_proj
      r: 8
      alpha: 8
      dropout: 0.1
      bias: none
    trajectory:
      num_poses: 10
      interval_length: 0.5
      time_horizon: 5.0
    tokens:
      action_start_id: 151665
      ignore_index: -100
      assistant_id:
      - 151644
      - 77091
    video:
      min_pixels: 109760
      max_pixels: 109760
  data:
    train:
      path: /data/zewei/DriveVLA/nuplan/placeholder/test
      scene_filter: /data/zewei/DriveVLA_RLFT/navsim/navsim/planning/script/config/common/train_test_split/scene_filter/navtest.yaml
      metric_cache_path: /data/dataset/navtest_metric_cache
      json_dataset_path: /data/dataset/nuplan/navtest_nocot
      sensor_data_path: /data/zewei/DriveVLA/nuplan/sensor_blobs/test
    val:
      path: /data/zewei/DriveVLA/nuplan/placeholder/test
      scene_filter: /data/zewei/DriveVLA_RLFT/navsim/navsim/planning/script/config/common/train_test_split/scene_filter/navtest.yaml
      metric_cache_path: /data/dataset/navtest_metric_cache
      json_dataset_path: /data/dataset/nuplan/navtest_nocot
      sensor_data_path: /data/zewei/DriveVLA/nuplan/sensor_blobs/test
  training:
    batch_size: 1
    learning_rate: 3.0e-05
    epochs: 1
    num_workers: 1
    weight_decay: 0.01
    devices:
    - 0
    - 1
    sample:
      max_length: 2048
      temperature: 0.2
      top_k: 0.0
      top_p: 1.0
  rl:
    kl_beta: 0.04
    reward:
      sliding_window_size: 100
      scale: 10
    cot_penalty:
      coef: 0.002
      center: 400.0
      weight: 0.3
  inference:
    batch_size: 1
    num_workers: 1
    max_length: 2048
    sample:
      temperature: 0.2
      top_k: 0.0
      top_p: 1.0
inference: false
